name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: setup Docker Build
      uses: docker/setup-buildx-action@v2.0.0
      
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
    # Artifact name
        name: programa
      
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
    # Username used to log against the Docker registry
        username: lucasfpnt
    # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.PASSWORD_DOCKER_LOGIN }}
        
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.0.0
      with:
    # Build's context is the set of files located in the specified PATH or URL
        context: .
    # Path to the Dockerfile
        file: ./Dockerfile
    # Push is a shorthand for --output=type=registry
        push: true
    # List of tags
        tags: lucasfpnt/go_cicd:${{github.ref_name}}
